version: '3.9'

services:

  pd:
    image: pingcap/pd:v6.1.1
    hostname: "pd{{.Task.Slot}}"
    entrypoint: [ "/bin/sh", "-c", "/pd-server --config=/pd.toml --data-dir=/data/$$HOSTNAME --name=$$HOSTNAME --advertise-client-urls=http://$$HOSTNAME:2379 --advertise-peer-urls=http://$$HOSTNAME:2380 --initial-cluster=pd1=http://pd1:2380,pd2=http://pd2:2380,pd3=http://pd3:2380" ]
    ports:
      - "2379:2379"
    volumes:
      - pd:/data
    networks:
      - network
    configs:
      - source: pd.toml
        target: /pd.toml
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.platform.os == linux

  tikv:
    image: pingcap/tikv:v6.1.1
    hostname: "tikv-{{.Node.Hostname}}"
    entrypoint: [ "/bin/sh", "-c", "/tikv-server --config=/tikv.toml --advertise-addr=$$HOSTNAME:20160 --data-dir=/data --pd=http://pd:2379" ]
    ports:
      - "20160:20160"
    volumes:
      - tikv:/data
    networks:
      - network
    configs:
      - source: tikv.toml
        target: /tikv.toml
    depends_on:
      - "pd"
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.platform.os == linux

  tidb:
    image: pingcap/tidb:v6.1.1
    hostname: "tidb"
    entrypoint: [ "/bin/sh", "-c", "/tidb-server --config=/tidb.toml --advertise-address=$$HOSTNAME --store=tikv --path=pd:2379" ]
    ports:
      - "4000:4000"
      - "10080:10080"
    networks:
      - network
    configs:
      - source: tidb.toml
        target: /tidb.toml
    deploy:
        replicas: 1

  # monitors
  pushgateway:
    image: prom/pushgateway:v0.3.1
    networks:
      - network
    command:
      - --log.level=error

  prometheus:
    user: root
    image: prom/prometheus:v2.2.1
    command:
      - --log.level=error
      - --storage.tsdb.path=/data/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - network
#    volumes:
#      - prometheus:/data
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - source: pd.rules.yml
        target: /etc/prometheus/pd.rules.yml
      - source: tikv.rules.yml
        target: /etc/prometheus/tikv.rules.yml
      - source: tidb.rules.yml
        target: /etc/prometheus/tidb.rules.yml

  tidb-vision:
    image: pingcap/tidb-vision:latest
    environment:
      PD_ENDPOINT: pd:2379
    ports:
      - "8010:8010"
    networks:
      - network

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8011:8978"
    networks:
      - network

configs:
  pd.toml:
    file: pd.toml
  tikv.toml:
    file: tikv.toml
  tidb.toml:
    file: tidb.toml
  prometheus.yml:
    file: prometheus.yml
  pd.rules.yml:
    file: pd.rules.yml
  tikv.rules.yml:
    file: tikv.rules.yml
  tidb.rules.yml:
    file: tidb.rules.yml

volumes:
  pd:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: tikv-pd
  tikv:
    driver: local

networks:
  network:
