version: '3.9'

services:

#  recursor:
#    image: powerdns/pdns-recursor-46:4.6.0 # the latest pdns-recursor from dockerhub
#    # the forward-zones are used to make sure the recursor asks the local authoritative server 
#    # about our own domains
#    command: --forward-zones=workload.stream=172.17.0.1:5300,lan=192.168.1.254:53 --local-address=0.0.0.0 --local-port=53 
#    networks:
#      - network
#    environment:
#      - PDNS_RECURSOR_API_KEY=onelongkey
#    ports:
#      - "53:53"
#      - "53:53/udp"
#      - "8082:8082" # HTTP API for the recursor

  auth:
    image: powerdns/pdns-auth-46:4.6.0 # latest pdns-authoritative nameserver image
    command: --local-address=0.0.0.0 --local-port=5300
    networks:
      - network
    user: root
    environment:
      - PDNS_AUTH_API_KEY=onelongkey
    ports:
      - "5300:5300"
      - "5300:5300/udp"
      # - "8081:8081" # HTTP API of the server
    volumes:
       - data:/var/lib/powerdns # file: pdns.sqlite3

  admin:
    image: ngoduykhanh/powerdns-admin:latest
    networks:
      - network
      - frontend_network
    volumes:
       - data:/data # file: powerdns-admin.db
    deploy:
      labels:
      - traefik.enable=true
      # admin interface
      - traefik.http.routers.powerdns.rule=PathPrefix(`/admin/powerdns`)
      - traefik.http.routers.powerdns.service=powerdns
      - traefik.http.routers.powerdns.entrypoints=admin
#      - traefik.http.routers.powerdns.middlewares=authelia@docker
      - traefik.http.services.powerdns.loadbalancer.server.port=80
    environment:
      - SCRIPT_NAME=/admin/powerdns
    healthcheck:
      disable: true # disabled health check because custom script name breaks it

networks:
  network:
    internal: true

volumes:
  data:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: powerdns
