version: '3.9'

services:

  auth:
    image: powerdns/pdns-auth-46:4.6.0 # latest pdns-authoritative nameserver image
    command: --local-address=0.0.0.0 --local-port=5300
    networks:
      - internal
    environment:
      - PDNS_AUTH_API_KEY=onelongkey
    ports:
      - "5300:53"
      - "5300:53/udp"
      # - "8081:8081" # HTTP API of the server
    volumes:
       - data:/var/lib/powerdns # file: pdns.sqlite3

  admin:
    image: ngoduykhanh/powerdns-admin:latest
    networks:
      - internal
      - frontend
    volumes:
       - data:/data # file: powerdns-admin.db
    deploy:
      labels:
      - traefik.enable=true
      # admin interface
      - traefik.http.routers.powerdns.rule=PathPrefix(`/admin/powerdns`)
      - traefik.http.routers.powerdns.service=powerdns
      - traefik.http.routers.powerdns.entrypoints=admin
#      - traefik.http.routers.powerdns.middlewares=authelia@docker
      - traefik.http.services.powerdns.loadbalancer.server.port=80
    environment:
      - SCRIPT_NAME=/admin/powerdns
    healthcheck:
      disable: true # disabled health check because custom script name breaks it

networks:
  frontend:
    external: true
  internal:
    external: true

volumes:
  data:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: powerdns
