version: '3.8'

services:

  frontend:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
      - 127.0.0.1:9080:9080 # admin port
    networks:
      - frontend
      - internal
    volumes:
      - traefik:/etc/traefik
      - letsencrypt:/letsencrypt
      - traefik-plugins:/plugins-local
    command:
      # logging
      - --accesslog=true
      - --log.level=DEBUG
      - --log.format=json
      # docker integration
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.endpoint=tcp://docker-socket:2375
      # incoming entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      # SSL certificate resolvers
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=pdns
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.disablepropagationcheck=true
      - --certificatesresolvers.letsencrypt.acme.email=hostmaster@workload.stream
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # admin interface
      - --api.dashboard=true
      - --entrypoints.admin.address=:9080
#      # plugins
#      - --experimental.localPlugins.rewrite.modulename=github.com/traefik/plugin-rewritebody
#      - --experimental.localPlugins.rewrite.version=v0.3.1
    environment:
      - PDNS_API_URL=http://dns-auth:8081/
      - PDNS_API_KEY=AsRtQU62xcwpLy3T!ufztH-btCtgH+pW
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      # admin interface
      - traefik.http.routers.dashboard.rule=PathPrefix(`/admin/traefik`) || HeadersRegexp(`Referer`, `.*\/admin\/traefik\/.*`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.entrypoints=admin
      - traefik.http.routers.dashboard.middlewares=traefik
      - traefik.http.middlewares.traefik.chain.middlewares=traefik-strip-prefix
      - traefik.http.middlewares.traefik-strip-prefix.stripprefix.prefixes=/admin/traefik

  docker-socket:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      SERVICES: 1
      SWARM: 1

volumes:
  traefik:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: traefik
  letsencrypt:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: letsencrypt
  traefik-plugins:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: traefik-plugins

networks:
  frontend:
    external: yes
  internal:
    external: yes
