version: '3.9'

services:

  ucarp:
    image: angzam78/ucarp
    command: adminpass 192.168.1.194
    secrets:
      - adminpass
    networks:
      - host
    cap_add:
      - NET_ADMIN
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux

secrets:
  adminpass:
    external: true

networks:
  host:
    name: host
    external: true
      
