version: '3.9'

services:

services:

  mysqld:
    hostname: mysqld-{{.Node.Hostname}}
    image: mysql:8.0.31
    volumes:
      - mysqld:/var/lib/mysql
    networks:
      - network
    secrets:
      - adminpass
    configs:
      - source: my.cnf
        target: /etc/mysql/conf.d/my.cnf
    environment:
      HOSTNAME: mysqld-{{.Node.Hostname}}
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/adminpass
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
          - node.platform.os == linux

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8979:80"
    networks:
      - network
    environment:
      - PMA_HOST=mysqld

configs:
  my.cnf:
    file: my.cnf
    template_driver: golang

secrets:
  adminpass:
    external: true

volumes:
  mysqld:

networks:
  network:

