version: '3.8'

services:

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:6.2.3-ubuntu
    secrets:
      - adminpass
    networks:
      - network
    restart: always
    ports:
      - '10051:10051'
    #volumes:
    #  - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=172.17.0.1
      - DB_SERVER_PORT=26257
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD_FILE=/run/secrets/adminpass

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:6.2.3-ubuntu
    secrets:
      - adminpass
    networks:
      - network
    restart: always
    ports:
      - '8083:8080'
    environment:
      - DB_SERVER_HOST=172.17.0.1
      - DB_SERVER_PORT=26257
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD_FILE=/run/secrets/adminpass
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network
    links:
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:6.2.3-alpine
    user: root
    networks:
      - network
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1

secrets:
  adminpass:
    external: true

networks:
  network:

