version: '3.8'

services:

  frontend:
    image: traefik:latest
    ports:
      - 443:443
      - 80:80
      - 9080:9080 # admin port
    networks:
      - frontend
      - internal
    configs:
      - source: traefik.yaml
        target: /etc/traefik/traefik.yaml
      - source: dynamic.yaml
        target: /etc/traefik/dynamic.yaml
    volumes:
      - traefik:/etc/traefik
      - letsencrypt:/letsencrypt
      - plugins:/plugins-local
#    command:
#      # plugins
#      - --experimental.localPlugins.rewrite.modulename=github.com/traefik/plugin-rewritebody
#      - --experimental.localPlugins.rewrite.version=v0.3.1
    deploy:
      labels:
        - traefik.enable=true
        # admin interface
        - traefik.http.routers.dashboard.rule=PathPrefix(`/admin/traefik`) || HeadersRegexp(`Referer`, `.*\/admin\/traefik\/.*`)
        - traefik.http.routers.dashboard.service=api@internal
        - traefik.http.routers.dashboard.entrypoints=admin
        - traefik.http.routers.dashboard.middlewares=traefik
        - traefik.http.middlewares.traefik.chain.middlewares=traefik-strip-prefix
        - traefik.http.middlewares.traefik-strip-prefix.stripprefix.prefixes=/admin/traefik
        - traefik.http.services.dashboardservice.loadbalancer.server.port=9080

  docker-socket:
    image: tecnativa/docker-socket-proxy
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      SERVICES: 1
      SWARM: 1
      NETWORKS: 1
      TASKS: 1

configs:
  dynamic.yaml:
    file: dynamic.yaml
  traefik.yaml:
    file: traefik.yaml.tmpl
    template_driver: golang

volumes:
  traefik:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: traefik
  letsencrypt:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: letsencrypt
  plugins:
    driver: juicefs:latest
    driver_opts:
      metaurl: postgres://juicefs:ju1cyPass@172.17.0.1:26257/juicefs_docker
      subdir: traefik-plugins

networks:
  frontend:
    external: yes
  internal:
    external: yes

