version: '3.9'

services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - NODE_ADDRESS=^10.0.*.*
    networks:
      - galera_network
    command: seed
    volumes:
      - seed:/var/lib/mysql
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password

  node:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.0.*.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - galera_network
    command: node tasks.seed,tasks.node
    volumes:
      - data:/var/lib/mysql
    secrets:
      - xtrabackup_password
    deploy:
      mode: replicated
      replicas: 0
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.platform.os == linux

volumes:
  data:
  seed:

networks:
  galera_network:
    driver: overlay

secrets:
  xtrabackup_password:
    file: secrets/xtrabackup_password
  mysql_password:
    file: secrets/mysql_password
  mysql_root_password:
    file: secrets/mysql_root_password
