version: '3.9'

services:

  roach:
    image: registry.viraqua.net/cockroachdb:v22.1.7-1663710783
    hostname: "roach{{.Task.Slot}}"
    command: start --certs-dir=/certs --join=roach1:26257,roach2:26257,roach3:26257
    ports:
      - "8081:8080"
      - "26257:26257"
    secrets:
      - source: node.key
        target: /certs/node.key
        mode: 0600
      - source: node.crt
        target: /certs/node.crt
        mode: 0644
      - source: ca.crt
        target: /certs/ca.crt
        mode: 0644
    volumes:
      - data:/cockroach/cockroach-data
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.platform.os == linux

secrets:
  node.key:
    file: certs/node.key
  node.crt:
    file: certs/node.crt
  ca.crt:
    file: certs/ca.crt

networks:
  network:

volumes:
  data:

