version: '3.9'

services:

  roach:
    image: registry.viraqua.net/cockroachdb:v22.1.7-1663710783
    hostname: "roach{{.Task.Slot}}"
    command: start --certs-dir=/certs --join=roach1:26257,roach2:26257,roach3:26257
    ports:
      - "8081:8080"
      - "26257:26257"
    secrets:
      - source: node.key
        target: /certs/node.key
        mode: 0600
      - source: node.crt
        target: /certs/node.crt
        mode: 0644
      - source: ca.crt
        target: /certs/ca.crt
        mode: 0644
    volumes:
      - data:/cockroach/cockroach-data
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
          - node.platform.os == linux

  pgweb:
    hostname: pgweb
    image: sosedoff/pgweb:latest
    ports:
      - 8082:8081
    networks:
      - network
      - frontend
    secrets:
      - adminpass
      - source: client.root.key
        target: /certs/client.root.key
        mode: 0600
      - source: client.root.crt
        target: /certs/client.root.crt
        mode: 0644
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.postgres.rule=PathPrefix(`/admin/postgres`) || HeadersRegexp(`Referer`, `.*\/admin\/postgres\/.*`)
        - traefik.http.routers.postgres.service=postgresservice
        - traefik.http.routers.postgres.entrypoints=admin
        - traefik.http.routers.postgres.middlewares=pgadmin
        - traefik.http.middlewares.pgadmin.chain.middlewares=pgadmin-strip-prefix
        - traefik.http.middlewares.pgadmin-strip-prefix.stripprefix.prefixes=/admin/postgres
        - traefik.http.services.postgresservice.loadbalancer.server.port=8081

secrets:
  node.key:
    file: certs/node.key
  node.crt:
    file: certs/node.crt
  ca.crt:
    file: certs/ca.crt

  client.root.crt:
    file: certs/client.root.crt
  client.root.key:
    file: certs/client.root.key

  adminpass:
    external: true

networks:
  network:
  frontend:
    external: true

volumes:
  data:

